services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    user: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      interval: 30s
      timeout: 10s
      retries: 5

  sonarqube:
    image: sonarqube:10.3-community
    container_name: sonarqube
    ports:
      - "9001:9000"
      - "9092:9092"
    volumes:
      - ./app-data/sonarqube/data:/opt/sonarqube/data
      - ./app-data/sonarqube/logs:/opt/sonarqube/logs
      - ./app-data/sonarqube/extensions:/opt/sonarqube/extensions

  mysql:
    image: mysql:5.7.16
    container_name: mysql
    environment:
      MYSQL_DATABASE: application_database
      MYSQL_PASSWORD: d3v5uch4ll3ng3
      MYSQL_ROOT_PASSWORD: d3v5uch4ll3ng3
    volumes:
      - ./app-data/mysql:/var/lib/mysql
      - ./initialization-scripts:/docker-entrypoint-initdb.d/:ro
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: d3v5uch4ll3ng3
    depends_on:
      mysql:
        condition: service_healthy

  api-ms-discovery-server:
    build:
      context: api-ms-discovery-server
    container_name: api-ms-discovery-server
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8761/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5

  api-ms-entry-gateway:
    build:
      context: api-ms-entry-gateway
    container_name: api-ms-entry-gateway
    environment:
      EUREKA_SERVER: http://api-ms-discovery-server:8761/eureka
    ports:
      - "9090:9090"
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/actuator/health" ]
    depends_on:
      api-ms-discovery-server:
        condition: service_healthy

  api-ms-customer-identity:
    build:
      context: api-ms-customer-identity
    container_name: api-ms-customer-identity
    environment:
      MYSQL_SERVER_IP: mysql
      MYSQL_SERVER_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: d3v5uch4ll3ng3
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      DISCOVERY_SERVER: http://api-ms-discovery-server:8761/eureka
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      api-ms-discovery-server:
        condition: service_healthy

  api-ms-financial-movement:
    build:
      context: ./api-ms-financial-movement
    container_name: api-ms-financial-movement
    environment:
      MYSQL_SERVER_IP: mysql
      MYSQL_SERVER_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: d3v5uch4ll3ng3
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      CUSTOMER_IDENTITY_ENDPOINT: http://api-ms-customer-identity:8081/customers
      DISCOVERY_SERVER: http://api-ms-discovery-server:8761/eureka
    ports:
      - "8082:8082"
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      api-ms-discovery-server:
        condition: service_healthy
